# _*_coding:utf-8_*_
# 作者:duningning.ming
# 创建时间: 2022/1/16 7:06 下午
# 文件   : mubu_login_test.py
# IDE   : PyCharm
# NOTE: Generated By HttpRunner v3.1.6
# FROM: har/mubu.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuLogin(HttpRunner):

    config = (
        Config("testcase description")
        .base_url("https://api2.$host/")
        .verify(False)
        .variables(**{
            "data_unique_id": "9a835035-8ab3-4775-8c27-573185dc3663",
            "csrf_token": "f058eca7-4abc-4d19-969b-6f19a47393b2",
            "host": "${get_test_host()}",
            "phone": "13271433391",
            "password": "ming6932058",
        })
        .export("jwttoken")
    )#全局变量设置 #27

    teststeps = [
        Step(
            RunRequest("/v3/api/user/phone_login")
            .post("/v3/api/user/phone_login")
            .with_headers(
                **{
                    "content-length": "65",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"',
                    "version": "3.0.0-2.0.0.1824",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
                    "data-unique-id": "9a835035-8ab3-4775-8c27-573185dc3663",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "",
                    "x-request-id": "${gen_random_request_id()}",#动态函数运算的引用
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {"phone": "${phone}", "password": "${password}", "callbackType": 0}
            )
            .extract()
            .with_jmespath('body.data.token',"jwttoken")
            .validate()
            .assert_equal("status_code", 200)
            #.assert_equal("body.code", 5)
        ),
        Step(
            RunRequest("/app")
            .get("https://${host}/app")
            .with_headers(
                **{
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-ch-ua-platform": '"macOS"',
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/home",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "9a835035-8ab3-4775-8c27-573185dc3663",
                    "csrf_token": "$csrf_token",
                    "SESSION": "1509130f-ac9d-42a0-9d62-b0cabf5b3ad1",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1641819354",
                    "_ga": "GA1.2.233353649.1641819355",
                    "_gid": "GA1.2.290704432.1641819355",
                    "SLARDAR_WEB_ID": "453f908a-edac-4b9d-b0e6-74e4f0c4f04e",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1641819402",
                    "Jwt-Token": "$jwttoken",
                }
            )
            .teardown_hook("${sleep(5)}")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("/v3/api/user/profile")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
                    "data-unique-id": "9a835035-8ab3-4775-8c27-573185dc3663",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "$jwttoken",
                    "sec-ch-ua-platform": '"macOS"',
                    "x-request-id": "${gen_random_request_id()}",
                    "version": "3.0.0-2.0.0.1824",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            #.assert_equal("body.code", 0)
            #.assert_greater_than("body.data.inviteCount",0)
        )
    ]


if __name__ == "__main__":
    TestCaseMubuLogin().test_start()
